#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

for f in /etc/X11/xinit/xinitrc.d/* /etc/profile.d/*.sh; do
  [ -x "$f" ] && . "$f"
done

unset f

. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" > /dev/null

while true; do
  dwm > ~/.local/share/dwm/dwm.log 2>&1
done

logout
