#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

for f in /etc/X11/xinit/xinitrc.d/*; do
  [ -x "$f" ] && . "$f"
done
unset f

. "$XDG_CONFIG_HOME/x11/xprofile" > /dev/null

export ZPOOL_VDEV_NAME_PATH=YES

xcape -e 'Control_L=Escape'

while true; do
  dwm
done

logout
