#!/bin/sh

wallpaper
setxkbmap gb
xrdb -merge ~/.config/x11/xresources
picom -b
xset r rate 300 50
xset s 1200
unclutter &
redshift -l 51.5:0 &
sxhkd &
bluetoothctl power on
davmail ~/.config/davmail/dylan.properties &
dunst &
xautolock -detectsleep -time 20 -corners 00+- -locker "slock" -killtime 20 -killer "sudo systemctl suspend" & 
safeeyes &
