#!/bin/sh

feh --bg-fill --no-fehbg -z -r ~/pictures/wallpapers/*
xrdb -merge ~/.config/x11/xresources
picom &
setxkbmap gb &
xset s noblank &
xset s off &
redshift -l 51.5:0 &
dunst &
safeeyes &
unclutter &
! pgrep -x mpd && mpd &
xautolock -notify 1 -notifier "notifyctl" -detectsleep -time 20 \
  -corners 0-+0 -locker "sleeper" -killtime 20 -killer "sleeper -s" &
davmail ~/.local/share/davmail/davmail.properties &
statusbar &
emacs --daemon=gui &
emacs --daemon=term &
