#!/bin/sh

# Inspired by https://bbs.archlinux.org/viewtopic.php?id=191555

add_modeline() {
	local modeline name
	modeline="$(cvt "$2" "$3" "$4" | sed -n 's/.*Modeline "\([^" ]\+\)" \(.*\)/\1 \2/p')"
	name="$(echo "${modeline}" | sed 's/\([^ ]\+\) .*/\1/')"
	if [ -z "${modeline}" -o -z "${name}" ] ; then
		echo "Error! modeline='${modeline}' name='${name}'"
		exit 1
	fi
	xrandr --delmode "$1" "${name}" 2>/dev/null
	xrandr --rmmode "${name}" 2>/dev/null
	xrandr --newmode ${modeline}
	xrandr --addmode "$1" "${name}"
	
	mid=$((($3-1080)/2))

  xrandr --output DisplayPort-0 --mode "${name}" --left-of eDP
  feh --bg-scale ~/.local/share/backgrounds/cyber.png --bg-scale ~/.local/share/backgrounds/arch.png
}

add_modeline DisplayPort-0 1920 1080 60
# x11vnc -viewonly -repeat -multiptr -usepw -noxrecord -noxfixes -noxdamage -wait 1 -defer 1 -overlay -forever -bg
