#!/usr/bin/env bash

# Basic vars
set shell bash
set cleaner ~/.config/lf/cleaner
set previewer ~/.config/lf/preview
set ratios 1:2:3
set drawbox true
# set preview true
set icons

# cmds/functions
cmd open ${{
    case $(file --mime-type "$f" -bL) in
        text/*|application/json) $EDITOR "$f";;
        *) xdg-open "$f" ;;
    esac
}}

cmd mkdir ${{
  printf "Directory Name: "
  read ans
  mkdir -p $ans
}}

cmd mkfile ${{
  printf "File Name: "
  read ans
  touch $ans
}}

cmd chmod ${{
  printf "Mode Bits: "
  read ans

  for file in "$fx"
  do
    chmod $ans $file
  done

  lf -remote 'send reload'
}}

cmd sudomkfile ${{
  printf "File Name: "
  read ans
  sudoedit $ans
}}

cmd setwallpaper feh --bg-scale "$f"

cmd fzf_jump ${{
  res="$(find . -maxdepth 3 | fzf --reverse --header='Jump to location')"
  if [ -f "$res" ]; then
    cmd="select"
  elif [ -d "$res" ]; then
    cmd="cd"
  fi
  lf -remote "send $id $cmd \"$res\""
}}

# Archive bindings
cmd unarchive ${{
  case "$f" in
      *.zip) unzip "$f" ;;
      *.tar.gz) tar -xzvf "$f" ;;
      *.tar.bz2) tar -xjvf "$f" ;;
      *.tar) tar -xvf "$f" ;;
      *) echo "Unsupported format" ;;
  esac
}}

cmd zip %zip -r "$f.zip" "$f"
cmd tar %tar cvf "$f.tar" "$f"
cmd targz %tar cvzf "$f.tar.gz" "$f"
cmd tarbz2 %tar cjvf "$f.tar.bz2" "$f"

# Trash cli bindings
cmd trash ${{
  files=$(printf "$fx" | tr '\n' ';')
  while [ "$files" ]; do
    # extract the substring from start of string up to delimiter.
    # this is the first "element" of the string.
    file=${files%%;*}

    trash-put "$(basename "$file")"
    # if there's only one element left, set `files` to an empty string.
    # this causes us to exit this `while` loop.
    # else, we delete the first "element" of the string from files, and move onto the next.
    if [ "$files" = "$file" ]; then
      files=''
    else
      files="${files#*;}"
    fi
  done
}}

cmd clear_trash %trash-empty

cmd restore_trash ${{
  trash-restore
}}

cmd stripspace %stripspace "$f"

# Bindings
# Remove some defaults
map m
map o
map n
map "'"
map '"'
map c
map e

# File Openers
map ee $$EDITOR "$f"
map f fzf_jump

# Archive Mappings
map az zip
map at tar
map ag targz
map ab tarbz2
map au extract

# Trash Mappings
# map dd trash
# map tc clear_trash
# map tr restore_trash

# Basic Functions
map . set hidden!
map D delete
map p paste
map y copy
map <enter> open
map mf mkfile
map mr sudomkfile
map md mkdir
map ch chmod
map bg setwallpaper
map r rename
map R reload
map C clear
map U unselect

# Movement
map gus cd /run/media/sda1

map gp. cd ~/Pictures
map gw. cd ~/Pictures/wallpapers
map gwr cd ~/Pictures/resources
map gws cd ~/Pictures/screenshots
map gww cd ~/Pictures/wallpapers/desktop
map gwm cd ~/Pictures/wallpapers/android

map gd cd ~/Documents

map gD cd ~/Downloads

map gs. cd ~/scripts

map gr. cd ~/repos
map grd cd ~/repos/dotfiles
map grw cd ~/repos/website

map gc cd ~/.config
map gl cd ~/.local
map gE cd /etc
map gU. cd /usr
map gUs cd /usr/share
