gui:
  showIcons: true
  theme:
    lightTheme: false # For terminals with a light background
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - red
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
os:
  editCommand: '$EDITOR'
confirmOnQuit: true
