#!/bin/sh

cd ~/Downloads/apps/

for f in *; do tar tf ../backup.tar | grep -F "$f" >> package.list; done
mv package.list ../shared/0/
cd ../shared/0/
for f in *; do tar tf ../../backup.tar | grep -F "$f" >> package.list; done
mv package.list ../../
cd ../../
tar cf restore.tar -T package.list 2>/dev/null
java -jar abe.jar pack restore.tar restore.ab
rm -r apps/ backup.tar restore.tar package.list shared/
