#!/bin/sh

mkdir -p ~/.tmp; cd ~/.tmp

rm -rf ~/.config/nvim.old
cp -r ~/.config/nvim ~/.config/nvim.old

git clone https://github.com/ChristianChiarulli/nvcode
rm -rf nvcode/.git* nvcode/LICENSE nvcode/README.md nvcode/utils
rsync -a nvcode/ ~/.config/nvim

options=( "settings" "java-ls" "colorscheme" "plugins" "dashboard" )
selected=( "$@" )

for i in `echo ${options[@]} ${selected[@]} | tr ' ' '\n' | sort | uniq -u`; do
	case $i in
		java-ls)
			cp -f ~/.config/nvim.old/lua/lsp/$i.lua ~/.config/nvim/lua/lsp/$i.lua
			;;
		dashboard)
			cp -f ~/.config/nvim.old/lua/nv-$i/init.lua ~/.config/nvim/lua/nv-$i/init.lua
			;;
		colorscheme|plugins)
			cp -f ~/.config/nvim.old/lua/$i.lua ~/.config/nvim/lua/$i.lua
			;;
        settings)
            cp -f ~/.config/nvim.old/nv-settings.lua ~/.config/nvim/nv-$i.lua
	esac
done

rm -rf nvcode
