#!/bin/sh

printf "Beginning upgrade.\\n"

sudo pacman -Sy && sudo powerpill -Su && paru -Su
pkill -RTMIN+8 "${STATUSBAR:-dwmblocks}"

printf "\\nUpgrade complete.\\nPress <Enter> to exit window.\\n\\n"
read -r _
