#!/bin/sh

# Prints the current volume or 🔇 if muted.

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e alsamixer ;;
	2) amixer set Master 1+ toggle > /dev/null;;
	4) amixer set Master on > /dev/null && amixer set Master 5%+ > /dev/null ;;
	5) amixer set Master on > /dev/null && amixer set Master 5%- > /dev/null;;
	3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

vol="$(amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1)"

[[ $(amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off) ]] && echo 🔇 0% && exit

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

echo "$icon$vol%"
