#!/usr/bin/env bash

# You can call this script like this:
# $ ./backlight up
# $ ./backlight down

# Script inspired by these wonderful people:
# https://github.com/dastorm/volume-notification-dunst/blob/master/volume.sh
# https://gist.github.com/sebastiencs/5d7227f388d93374cebdf72e783fbd6a
# https://gist.github.com/Blaradox/030f06d165a82583ae817ee954438f2e


function get_icon {
  level=$(get_brightness)
  case $((
    level > 0 && level < 10     ? 1 :
    level >= 10 && level < 30   ? 2 :
    level >= 30 && level < 70   ? 3 :
    level >= 70 && level <= 100 ? 4 : 0)) in
    (0) echo "/usr/share/icons/Papirus-Dark/48x48/status/notification-display-brightness-off.svg";;
    (1) echo "/usr/share/icons/Papirus-Dark/48x48/status/notification-display-brightness-low.svg";;
    (2) echo "/usr/share/icons/Papirus-Dark/48x48/status/notification-display-brightness-medium.svg";;
    (3) echo "/usr/share/icons/Papirus-Dark/48x48/status/notification-display-brightness-high.svg";;
    (4) echo "/usr/share/icons/Papirus-Dark/48x48/status/notification-display-brightness-full.svg";;
  esac
}

function get_brightness {
  light -G | cut -d '.' -f 1
}

function send_notification {
  icon=`get_icon`
  brightness=`get_brightness`
  # Make the bar with the special character ┃ (it's not pipe |)
  # https://en.wikipedia.org/wiki/Box-drawing_character
  bar=$(seq -s "┃" 0 $((brightness / 5)) | sed 's/[0-9]//g')
  # Send the notification
  dunstify -i "$icon" -r 5555 -u low "$brightness   $bar"
}

case $1 in
  up)
    # increase the backlight by 10%
    light -A 10
    send_notification
    ;;
  down)
    # decrease the backlight by 10%
    light -U 10
    send_notification
    ;;
esac
