#!/usr/bin/python

# Inspired by dunst issue https://github.com/dunst-project/dunst/issues/645#issuecomment-774522304

import os
from sys import argv

blacklist = ["Spotify", "dunstify", "Brave"] 
sound = os.getcwd() + "/.config/dunst/sounds/%s.wav"

os.system('echo "%s" > notify-send.log' % (argv[0] + argv[1] + argv[2]))

if argv[1] not in blacklist:
    if os.path.exists(sound % argv[1]):
        os.system("aplay '%s'" % sound % argv[1])
    else:
        os.system("aplay %s" % sound % "alert")

