#!/bin/sh

export XDG_RUNTIME_DIR=/run/user/$(id -u)
export DISPLAY=:0

status=`udevadm info --path=/sys/class/power_supply/BAT0 | sed -n -e 's/^.*POWER_SUPPLY_STATUS=//p'`
capacity=`udevadm info --path=/sys/class/power_supply/BAT0 | sed -n -e 's/^.*POWER_SUPPLY_CAPACITY=//p'`

if [ $status = Discharging ]; then
	if [ $capacity -lt 5 ]; then
		logger "Critical battery threshold"
		sudo systemctl hibernate
	elif [ $capacity -lt 20 ]; then
		logger "Low battery threshold"
		! pgrep -x swaynag && swaynag -m 'Low Battery!'
	fi
fi

