#!/bin/sh

if [[ -z $SWAYSOCK ]]; then
    export SWAYSOCK=/run/user/$(id -u)/sway-ipc.$(id -u).$(pgrep -x sway).sock
fi

swaymsg output '*' background $(find $HOME/Pictures/wallpapers/desktop -type f | shuf -n 1) fill
