#!/usr/bin/env bash

# You can call this script like this:
# $./microphone up
# $./microphone down
# $./microphone mute

# Script modified from these wonderful people:
# https://github.com/dastorm/volume-notification-dunst/blob/master/volume.sh
# https://gist.github.com/sebastiencs/5d7227f388d93374cebdf72e783fbd6a
# https://gist.github.com/Blaradox/030f06d165a82583ae817ee954438f2e


function get_icon {
  level=`get_volume`
  is_mute && muted=1 || muted=0
  case $((
    level > 0 && level < 30 && muted==0     ? 1 :
    level >= 30 && level < 70 && muted==0   ? 2 :
    level >= 70 && level <= 100 && muted==0 ? 3 : 0)) in
    (0) echo "/usr/share/icons/Papirus-Light/48x48/status/microphone-sensitivity-muted.svg";;
    (1) echo "/usr/share/icons/Papirus-Light/48x48/status/microphone-sensitivity-low.svg";;
    (2) echo "/usr/share/icons/Papirus-Light/48x48/status/microphone-sensitivity-medium.svg";;
    (3) echo "/usr/share/icons/Papirus-Light/48x48/status/microphone-sensitivity-high.svg";;
  esac
}

function get_volume {
    amixer get Capture | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
    amixer get Capture | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function send_notification {
  icon=`get_icon`
  volume=Mute
  if ! is_mute; then
      volume=`get_volume`
      # Make the bar with the special character ┃ (it's not pipe |)
      # https://en.wikipedia.org/wiki/Box-drawing_character
      bar=$(seq -s "┃" 0 $((volume / 5)) | sed 's/[0-9]//g')
  fi
  # Send the notification
  dunstify -i "$icon" -r 2000 -u low "$volume   $bar"
}

case $1 in
  up)
    amixer set Capture cap > /dev/null
    amixer set Capture 5%+ > /dev/null
    send_notification
    ;;
  down)
    amixer set Capture cap > /dev/null
    amixer set Capture 5%- > /dev/null
    send_notification
    ;;
  mute)
    amixer set Capture toggle > /dev/null
    send_notification
    ;;
esac
